### ISSUE TITLE
feat(proj): Initial Template To-Do

### ISSUE THREAD

**Issue by HarryET** [HarryET/gleam-intellij#6]
- [x] Create a new [IntelliJ Platform Plugin Template][template] project.
- [x] Get familiar with the [template documentation][template].
- [x] Verify the [pluginGroup](https://github.com/HarryET/gleam-intellij/tree/main/gradle.properties), [plugin ID](https://github.com/HarryET/gleam-intellij/tree/main/src/main/resources/META-INF/plugin.xml) and [sources package](https://github.com/HarryET/gleam-intellij/tree/main/src/main/kotlin).
- [x] Review the [Legal Agreements](https://plugins.jetbrains.com/docs/marketplace/legal-agreements.html).
- [x] [Publish a plugin manually](https://plugins.jetbrains.com/docs/intellij/publishing-plugin.html?from=IJPluginTemplate) for the first time.
- [x] Set the Plugin ID in the above README badges.
- [x] Set the [Deployment Token](https://plugins.jetbrains.com/docs/marketplace/plugin-upload.html).
- [ ] Click the <kbd>Watch</kbd> button on the top of the [IntelliJ Platform Plugin Template][template] to be notified about releases containing new features and fixes.

[template]: https://github.com/JetBrains/intellij-platform-plugin-template
